### ISSUE TITLE
this profile is not available

### ISSUE THREAD

**Issue by jayhill365** [itsnbyim/LInBot#9]
Everything seems to be working fine. However when I start bot it tells me to make an edit to line 205 in the file LInBot.py so when attempting to make this I go back in and look at line 205 and there isn't the text  " BeautifulSoup([your markup]) " that the terminal is telling me to change. I'll put some screen shoots up here to help clarify. Also Chrome starts up but says profile can't be found. Would Appreciate if anyone could Help! 

<img width="1434" alt="screen shot 2017-05-03 at 12 11 55 pm" src="https://cloud.githubusercontent.com/assets/19259608/25677163/bfec0686-2ff9-11e7-9f57-c32231e17f6f.png">
<img width="572" alt="screen shot 2017-05-03 at 12 07 27 pm" src="https://cloud.githubusercontent.com/assets/19259608/25677113/9a169bf6-2ff9-11e7-9ee7-40afd96fad44.png">
<img width="1059" alt="screen shot 2017-05-03 at 12 11 18 pm" src="https://cloud.githubusercontent.com/assets/19259608/25677123/a35b28d0-2ff9-11e7-861c-776024281c89.png">

**Comment by hoangsoft90** [comment]
yes, i face the same issue. Because linkedin profile id not only number.

**Comment by rodrigolopezguerra** [comment]
that's correct , in fact id's are not being used anymore. 
The warning and the second print screen are not relared. You can check the parsers that can be used here https://www.crummy.com/software/BeautifulSoup/bs4/doc/ in the section "installing a parser"


Here's a way to get the profiles link from the search page 

`def getProfilesLinks(soup):
	profiles = []
	for link in soup.find('div', {'class':'blended-srp-results-js'}).find('ul', {'class':'search-results__list list-style-none'}).findAll('li', {'class':'search-result search-result__occluded-item ember-view'}):
		try:
			profiles.append(link.find('a',{'class':'search-result__result-link ember-view'}).get('href')).click()
		except:
			pass
	return profiles`

**Comment by jayhill365** [comment]
RIP
